### PR TITLE
Ported word2vec to Python 3

### PR DESCRIPTION
**Pull request by stephenbalaban**

### CODE REVIEW

**Comment by terrex** [comment]
+1

**Comment by danielfrg** [comment]
Hi guys, 

First,  thanks @stephenbalaban for the PR :)

I definitely want to merge this but i need to test it first and i want to be sure it still works on python 2 and 3, i'll do my best to get some time this weekend.

Also want to take this chance to write like some very simple tests and get travisci working on both python 2 and 3.

**Comment by stephenbalaban** [comment]
I didn't port for backwards compatibility :). There will definitely be some work to make sure this runs in python 2 as well. But yea, @danielfrg I think some tests would be worthwhile.

**Comment by danielfrg** [comment]
Master should support Python 2.7 and Python 3.4 now. Feel free to test it and open new issues if you find errors

**Pull request merged**
